### ISSUE TITLE
[Feature] Hide SourceTV spectator bot from player listing

### ISSUE THREAD

**Issue by xedmain** [GleammerRay/INTERLINKED#7]
When querying a server, it's possible to get the name for the spectator SourceTV bot, so wouldn't it be possible to hide it when clicking on the "Show players" button? As of right now, if you click on it, it properly shows the number of online players, but the SourceTV bot is still in the list.

**Comment by GleammerRay** [comment]
Resolved in https://github.com/GleammerRay/INTERLINKED/releases/tag/v7.3.1. Thank you!
